name: Deploy SQL Schema changes

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SQL Server Tools & SqlPackage
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          wget -qO- https://aka.ms/sqlpackage-linux | tar xz
          echo 'export PATH="$PATH:$PWD"' >> ~/.bashrc
          source ~/.bashrc

      - name: Deploy Schema Changes to MSSQL Server
        run: |
          sqlpackage /Action:Publish \
                     /SourceFile:deploy/YourDatabase.dacpac \
                     /TargetServerName:${{ secrets.DB_SERVER }} \
                     /TargetDatabaseName:YourDatabase \
                     /TargetUser:${{ secrets.DB_USER }} \
                     /TargetPassword:${{ secrets.DB_PASSWORD }}
        env:
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
