name: Deploy SQL Schema changes

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SQL Server Tools & SqlPackage
        run: |
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo add-apt-repository "$(curl -s https://packages.microsoft.com/config/ubuntu/20.04/prod.list)"
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Deploy Schema Changes to MSSQL Server
        run: |
          sqlpackage /Action:Publish \
                     /SourceFile:deploy/YourDatabase.dacpac \
                     /TargetServerName:${{ secrets.DB_SERVER }} \
                     /TargetDatabaseName:YourDatabase \
                     /TargetUser:${{ secrets.DB_USER }} \
                     /TargetPassword:${{ secrets.DB_PASSWORD }}
        env:
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
